version: '3'

services:
  pqai_classifier:
    image: pqai_classifier
    container_name: pqai_classifier
    build: .
    restart: always
    volumes:
      - type: bind
        source: ./assets
        target: /app/assets
    ports:
      - ${PORT}:80
    environment:
      - PORT=${PORT}
